global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: 'movie-reservation'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'movie-reservation:8080' ]
        labels:
          application: 'Movie Reservation'