server:
  port: 8080

spring:
  config:
    activate:
      on-profile: prod
  application:
    name: moviereservation
  datasource:
    url: jdbc:postgresql://localhost:5432/movies
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: 'false'

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
