server:
  port: 8080

spring:
  config:
    activate:
      on-profile: prod
  application:
    name: moviereservation
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/moviereservation
    password: 123456
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: 'false'

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
